### PR TITLE
Multiple container and destroy

### PR DESCRIPTION
**Pull request by vogdb**
Depends on #27 
Functionality to have multiple unveil instances on page and destroy unveil instance.

### CODE REVIEW

**Comment by vogdb** [comment]
Don't forget to update docu! (to myself)

**Comment by hongaar** [comment]
Hey @vogdb thanks for your multiple PR's! Will review asap.

**Review by hongaar — CHANGES_REQUESTED** [review]
Hi @vogdb sorry to keep you waiting for so long.. I finally found some time this week to work on this :)

Thanks for contribution and excited to see this repo going forward!

- Does this contain any backward incompatible changes?
- Please update the documentation.
- Please update the dist version with `grunt build`.
- Dist version goes from ~2kb to ~3kb, which is a ~50% increase. Can these changes be compressed somehow?

~~Once those changes are in, could you open a new PR on the `develop` branch?~~ Can now be done in GitHub without opening new PR by changing base branch of existing PR, yay!

**Comment by vogdb** [comment]
> Does this contain any backward incompatible changes?

Well, destroying now happens differently. We should trigger `destroy.unveil` instead of just taking off listeners. The rest is compatible.

> Dist version goes from ~2kb to ~3kb, which is a ~50% increase. Can these changes be compressed somehow?

I've reused `unveil` const everywhere I could. Not sure about other parts. Logging can be definitely optimised if we move `console.log` call to separate function. Is 3kb that painful?

**Comment by vogdb** [comment]
@hongaar please look again

**Review by hongaar — APPROVED** [review]

**Comment by hongaar** [comment]
@vogdb Thanks, now merged!

Will remove the call to Sauce for now until I figure out what's tripping it up so we have a proper build status again :)

Concerning the filesize, it's easy to add code and difficult to remove code, so I think it's a good to critically consider each feature which adds weight to the resulting lib. It's just one dependency of probably several for most websites, and I always like it when I can keep vendor bytes down to a minimum.

As for the console.log calls, they're automatically removed in the dist version.

**Comment by vogdb** [comment]
Thank you so much!

**Pull request merged**
